spring.application.name=springboot_security_http_baasic

spring.datasource.url=jdbc:postgresql://localhost:5433/springboot
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
#database dan entity dagi table bomi yoqmi tekshiradi bolsa update qiladi, bolmasa create qiladi
spring.jpa.hibernate.ddl-auto=update
# bolsa drop qiladi va create qiladi
#spring.jpa.hibernate.ddl-auto=create
# bolsa drop qiladi va create qiladi server ochganda yana drop qiladi iz qolmaydi
#spring.jpa.hibernate.ddl-auto=create-drop
# Entity table dagi column database dagi table da yoq bolsa shuni aytib beradi
#spring.jpa.hibernate.ddl-auto=valided
# Hechqanday database da yangi table yaratmaydi va ochirmaydi
#spring.jpa.hibernate.ddl-auto=none -> shu yoldan foydalanamiz real proyektda
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=ali123
spring.security.user.password=123123
spring.security.user.roles=ADMIN, USER


