spring.application.name=springboot_security_http_baasic

spring.datasource.url=jdbc:postgresql://localhost:5433/spring_security
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.user.name=ali123
spring.security.user.password=123123
spring.security.user.roles=ADMIN, USER
